### ISSUE TITLE
Is there any relation between struct in main.c and stat.h in Linux?

### ISSUE THREAD

**Issue by Biswa96** [dmex/lxssattr#3]
I've gone through your project and I've some questions. Where did you get that lxss extended attributes struct? I find some similarities between that and stat.h header file in Linux. Can I add the inode details in that struct (like in stat command)?
Can I add your idea in my repo?

**Comment by dmex** [comment]
> I find some similarities between that and stat.h header file in Linux.

Linux filesystems use the stat structure and WSL hosts a linux environment.

> Can I add the inode details in that struct (like in stat command)?

I might have used the incorrect types. Try change the st_mode field from ULONG to USHORT like this:

> typedef struct _LXSS_FILE_EXTENDED_ATTRIBUTES_V1
> {
>     USHORT Flags;
>     USHORT Version;
>     **USHORT st_ino; // Inode number** 
>     USHORT st_mode;       // Mode bit mask constants
>     ULONG st_uid;        // Numeric identifier of user who owns file (Linux-specific).
>     ULONG st_gid;        // Numeric identifier of group that owns the file (Linux-specific)
>     ULONG st_rdev;       // Drive number of the disk containing the file.
>     ULONG st_atime_nsec; // Time of last access of file (nano-seconds).
>     ULONG st_mtime_nsec; // Time of last modification of file (nano-seconds).
>     ULONG st_ctime_nsec; // Time of creation of file (nano-seconds).
>     ULONG64 st_atime;    // Time of last access of file.
>     ULONG64 st_mtime;    // Time of last modification of file.
>     ULONG64 st_ctime;    // Time of creation of file.
> } LXSS_FILE_EXTENDED_ATTRIBUTES_V1, *PLXSS_FILE_EXTENDED_ATTRIBUTES_V1;

**Comment by Biswa96** [comment]
You don't answer my first question. How did you get that struct? Or where can I read about that struct?
Also I don't understand the memory copy between LXSS_FILE_EXTENDED_ATTRIBUTES_V1 struct and FILE_FULL_EA_INFORMATION struct with RtlCopyMemory?

**Comment by Biswa96** [comment]
NtQueryEaFile() may not give inode details. I've checked the output buffer of that function and it gives same result of `/init` after installing and uninstalling a distro.

**Comment by Biswa96** [comment]
How to seperate file permission and file details from `mode` variable?

 As example, `0x81ff` in Hex can be represented as `100777` in Oct. 

That can be seperated as `100777 = 100000 + 777` where `777` is `rxwrxwrxw` and `100000` represents file.

**Comment by Biswa96** [comment]
I found my answer into this article: https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/ and the quote is:

>The remaining inode attributes, such as inode number and file size, are derived from information kept by NTFS.

**Comment by dmex** [comment]
@Biswa96 

Thanks, I'll add the code to query the inode soonish :)

If you need to query the inode from Windows (without waiting for me to update the tool) then just use the "fsutil file queryfileid" command and convert the hex to decimal. For example:

"fsutil file queryfileid \rootfs\bin\bash" on my machine returns:
`File ID is 0x000000000000000000050000000021b9`

Converted to decimal:
1407374883561913

```
dmex@dmex-pc:~$ stat /bin/bash
  File: '/bin/bash'
  Size: 1037528         Blocks: 2032       IO Block: 512    regular file
Device: 2h/2d   Inode: 1407374883561913
```

**Comment by Biswa96** [comment]
Is there any way to know that a Linux file is a symlink/hardlink from Win32 console apps?
When I use `_stat()` in Windows it (stat.st_mode) always returns simple file type.

**Comment by dmex** [comment]
> When I use _stat() in Windows

That doesn't produce the same result because the WSL environment doesn't use NTFS file attributes. 

When you call _stat() from Windows; The data is read from the NTFS file attributes.
When you call _stat() from within the WSL environment; The data is read from the LXATTRB extended attribute. 

You can see the source for _stat() by locating the common_stat_handle_file_opened function inside this file: "C:\Program Files (x86)\Windows Kits\10\Source\<ANY_VERSION>\ucrt\filesystem\stat.cpp"

> Is there any way to know that a Linux file is a symlink/hardlink from Win32 console apps?

Yes. You need to use the st_mode field from the LXSS_FILE_EXTENDED_ATTRIBUTES_V1 structure. The st_mode will include the L permission which indicates the file is a link.

See also: 
https://github.com/dmex/lxssattr/blob/master/lxssattr/posix.c#L44

**Comment by Biswa96** [comment]
I'm waiting that type of answer. Here I add some details.

When I install any distro LxssManager.dll will set the LXATTRB for that symlink with NtSetEaFile(). So that anyone can read the `st_mode` as symlink.
But when I extract the symlink from .tar.gz with 7zip or any Win app (no LXATTRB applied), the st_mode shows it as normal file.

The second one is my problem. In other version you may think my question is: How does LxssManager know which file is symlink or normal file in .tar.gz?

**Comment by dmex** [comment]
> But when I extract the symlink from .tar.gz with 7zip or any Win app (no LXATTRB applied), the st_mode shows it as normal file.

WSL has some weird undocumented behavior in that scenario. You can create your own LXATTRB structure and write that to the file using NtSetEaFile just like LxssManager.dll does... This is exactly what projects like [WSL-Distribution-Switcher ](https://github.com/RoliSoft/WSL-Distribution-Switcher) do when installing a distro.

However, It'll only work for files located within the rootfs directory for a distro... Consider this test case:

cd /mnt/d/
touch test
ln -s test testlink

WSL can query the attributes for both the test and testlink files but you can't query the LXATTRB structure for those files from Windows. I also don't know where WSL is storing the LXATTRB structure for files located outside the rootfs directory as yet.

This seems to be both a security and compatibility feature. 

1) If multiple distributions are installed then you don't want them both using the same LXATTRB structure for files outside rootfs since it'll cause security/stability/compatibility issues.

2) To prevent Windows applications from downloading files from the internet, writing the LXATTRB structure with 0 (root) for GID/UID and then using the [WslLaunch function](https://msdn.microsoft.com/en-us/library/windows/desktop/mt826868.aspx) to execute that file as the root user inside the WSL environment.

You could try querying the roofs directory from the registry, copy files into that directory and set the LXATTRB structure using NtSetEaFile?

**Comment by Biswa96** [comment]
Ok, I shall try.  Now I'm going to sleep in my country time.

**Comment by dmex** [comment]
@Biswa96 

> How does LxssManager know which file is symlink or normal file in .tar.gz?

The gz compression format includes an attributes field for each compressed file and also preserves symlink target information. You can also see that information using a GUI decompression tool like 7-ZIP.

Btw, the latest win10 update (1803) includes a new structure for querying the LXATTR information using the NtQueryInformationFile function and setting with NtSetInformationFile via a new class called FileStatLxInformation (70)

```
typedef struct _FILE_STAT_LX_INFORMATION
{
    LARGE_INTEGER FileId;
    LARGE_INTEGER CreationTime;
    LARGE_INTEGER LastAccessTime;
    LARGE_INTEGER LastWriteTime;
    LARGE_INTEGER ChangeTime;
    LARGE_INTEGER AllocationSize;
    LARGE_INTEGER EndOfFile;
    ULONG FileAttributes;
    ULONG ReparseTag;
    ULONG NumberOfLinks;
    ULONG EffectiveAccess;
    ULONG LxFlags;
    ULONG LxUid;
    ULONG LxGid;
    ULONG LxMode;
    ULONG LxDeviceIdMajor;
    ULONG LxDeviceIdMinor;
} FILE_STAT_LX_INFORMATION, *PFILE_STAT_LX_INFORMATION;
```

**Comment by Biswa96** [comment]
I know about the class. But I checked LxssManager.dll in IDA. It uses NtQueryInformationFile with 71 to get/set case sensitivity.

**Comment by dmex** [comment]
@Biswa96 

FileCaseSensitiveInformation is class 71... Here's the type from symbols:

```
typedef struct _FILE_CASE_SENSITIVE_INFORMATION
{
    ULONG Flags;
} FILE_CASE_SENSITIVE_INFORMATION, *PFILE_CASE_SENSITIVE_INFORMATION;
```

**Comment by Biswa96** [comment]
I know that. In my previous post I said that I didn't find in IDA that LxssManager.dll uses the "70" class. Are those classes in SDK or WDK? Did you find your "LXSS_FILE_EXTENDED_ATTRIBUTES_V1" struct? Is it close source?
